### ISSUE TITLE
pls add multiboxing support

### ISSUE THREAD

**Issue by anywayaura** [HeavyMetalPirate/GW2Nexus-RegionsOfTyria#1]
it just flickers on both windows, if characters are in different zones...

**Comment by DeltaGW2** [comment]
This is an issue with how you multibox, not with Nexus (or this addon) itself.
The start parameter `-mumble` allows to change the name of the MumbleLink used. If you do not set it, both game clients will access and write to a file called just `MumbleLink`, hence the flickering.

GW2Launcher and Launchbuddy, both support setting a custom MumbleLink per account/client.

**Comment by anywayaura** [comment]
Thank you very much!
